'''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed N,
    find the sum of the even-valued terms.

    1 <= N <= 4*(10**12)
'''

sequence = [1, 2]
sum = 0

upper_limit = int(input('Enter upper limit for sum of terms in Fibonacci :: '))
if upper_limit > 1:
    sum += 2

term = 0
while term <= upper_limit:
    term = sequence[0] + sequence[1]
    sequence[0] = sequence[1]
    sequence[1] = term

    if term & 1 != 1 and term <= upper_limit:
        sum += term

print('Sum of even valued Fibonacci terms that do not exceeds {} is {}'.format(upper_limit, sum))